version: '3.8'
services:
  nest-api7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api7
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - common

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common
volumes:
  postgres:
    name: nest-prisma-docker-db
networks:
  common:
    driver: bridge
